"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g transform={"translate(17,15) rotate(0,0,0) scale(1.35,1.35)"}>
        <animateTransform attributeName="transform" type="translate" values={"17,15;15.01,16.99;16,16"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1.35,1.35;1.1,1.1;0.8,0.8"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="m10.586 5.414-5.172 5.172" transform={"translate(-8,-8)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 2: path */}
      <g transform={"translate(23,25) rotate(0,0,0) scale(1.25,1.25)"}>
        <animateTransform attributeName="transform" type="translate" values={"23,25;25,23;24,24"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;1,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1.25,1.25;1.2,1.2;0.8,0.8"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="m18.586 13.414-5.172 5.172" transform={"translate(-16,-16)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 3: path */}
      <g transform={"translate(20,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20.42,19.92;20,20"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;-9.87,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1.24,1.24;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="M6 12h12" transform={"translate(-12,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 4: circle */}
      <g transform={"translate(17.84,30) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"17.84,30;20,28;20,28"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 5: circle */}
      <g transform={"translate(22.16,9.36) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"22.16,9.36;20,12;20,12"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.39;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 6: circle */}
      <g transform={"translate(28,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"28,20;30.08,18.16;28,20"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 7: circle */}
      <g transform={"translate(12,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"12,20;11.04,22.08;12,20"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.385;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}