"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,19.91;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.495;1"} keySplines={"0 0 1 1;0.87 0 0.13 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;5,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.495;1"} keySplines={"0 0 1 1;0.87 0 0.13 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1.4,1.4;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.495;1"} keySplines={"0 0 1 1;0.87 0 0.13 1"} additive="replace" />
            <path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" transform={"translate(-12,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"14.8,19.94;14.8,19.94;14.79,19.94;14.78,19.94;14.78,19.94;14.78,19.94"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.02,0.02;0.02,0.02;0,0;0.02,0.02;0,0;0.02,0.02"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 3: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"19.56,19.9;19.54,19.86;19.58,19.78;19.52,19.76;19.62,19.88"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.4975;0.7525;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.4975;0.7525;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0,0;0.02,0.02;0,0;0.02,0.02;0.02,0.02"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.4975;0.7525;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 4: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"14.8,19.94;14.8,19.94;14.8,19.94;14.8,19.94;14.8,19.94"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.02,0.02;0,0;0.02,0.02;0,0;0.02,0.02"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 5: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"25.1,19.86;25.1,19.86;25.14,19.82;25.1,19.82;25.06,19.74;25.12,19.82"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0,0;0,0;0.02,0.02;0.02,0.02;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;0.25;0.5;0.75;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}