"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"14,18;14,18;14,18"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.625;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.625;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.625;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.625;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M3 7v6h6" transform={"translate(-6,-10)"} strokeDasharray={12} strokeDashoffset={12} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"12;0;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.625;1"} keySplines={"0 0 1 1;0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,20.5;20,20.5;20,20.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.6275;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.6275;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.6275;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.6275;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M21 17a9 9 0 0 0-9-9 9 9 0 0 0-6 2.3L3 13" transform={"translate(-12,-12.5)"} strokeDasharray={24.74} strokeDashoffset={24.74} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"24.74;0;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.6275;1"} keySplines={"0 0 1 1;0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}