"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g transform={"translate(16,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"16,20;16,20;16,20;16,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;15,0,0;-15,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="M10 9.17a3 3 0 1 0 0 5.66" transform={"translate(-8,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 2: path */}
      <g transform={"translate(23,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"23,20;23,20;23,20;23,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;15,0,0;-15,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="M17 9.17a3 3 0 1 0 0 5.66" transform={"translate(-15,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 3: rect */}
      <g transform={"translate(20,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,20;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1.1,1.1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <rect x={-10} y={-7} width={20} height={14} rx={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}