"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g transform={"translate(21,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"21,20;21.74,19.84;21.66,20.57;21,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.36;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;-6.18,0,0;6.4,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.36;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.36;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z" transform={"translate(-13,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}