"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: rect */}
      <g transform={"translate(20,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="sum" />
        <rect x={-9} y={-9} width={18} height={18} rx={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 2: circle */}
      <g transform={"translate(13.26,25.82) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"13.26,25.82;13.99,21.55;15.53,17.33;19.23,15.22;23.27,14.48;26.74,16.55"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.2;0.3925;0.6;0.8025;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.2;0.3925;0.6;0.8025;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1;1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.2;0.3925;0.6;0.8025;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={2} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 3: path */}
      <g transform={"translate(21.5,24.16) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"21.5,24.16;20.25,23.79;21.5,24.16"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.475;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.475;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1.1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.475;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" transform={"translate(-13.5,-16.16)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}