"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"10,19.5;10,19.5;10,19.5;10,19.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,2.54;1,1.16;1,1.89;1,1.09"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M2 10v3" transform={"translate(-2,-11.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"14,19.5;14,19.5;14,19.5;14,19.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1.99;1,1.39;1,1.63;1,0.89"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M6 6v11" transform={"translate(-6,-11.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>

      {/* Element 3: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"18,20;18,20;18,20;18,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,0.75;1,0.49;1,0.3;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M10 3v18" transform={"translate(-10,-12)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>

      {/* Element 4: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"22,19.5;22,19.5;22,19.5;22,19.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,0.73;1,2.38;1,3.13;1,1.48"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M14 8v7" transform={"translate(-14,-11.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>

      {/* Element 5: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"26,19.5;26,19.5;26,19.5;26,19.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1.35;1,0.34;1,1.08;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M18 5v13" transform={"translate(-18,-11.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>

      {/* Element 6: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"30,19.5;30,19.5;30,19.5;30,19.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1.15;1,6.75;1,1.33;1,2.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3325;0.6675;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M22 10v3" transform={"translate(-22,-11.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
            </g>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}