"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: line */}
      <g transform={"translate(4.81,19.07) rotate(37,0,0) scale(0.01,0.01)"}>
        <animateTransform attributeName="transform" type="translate" values={"4.81,19.07;10.94,23.91;10.96,23.92"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"37,0,0;37,0,0;37,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;1,1;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <line x1={6.5} y1={0} x2={-6.5} y2={0} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 2: line */}
      <g transform={"translate(16.26,27.85) rotate(-40,0,0) scale(0,0)"}>
        <animateTransform attributeName="transform" type="translate" values={"16.26,27.85;16.26,27.85;26.19,19.44"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"-40,0,0;-40,0,0;-40,0,0"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"0,0;0,0;1,1"} dur={"2s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.215;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <line x1={-13} y1={0} x2={13} y2={0} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}