"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g transform={"translate(23,18.5) rotate(1,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"23,18.5;22.3,16.93;23,18.5;23,18.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;0.9975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"1,0,0;10,0,0;1,0,0;1,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;0.9975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1.2;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;0.9975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <path d="M9 18V5l12-2v13" transform={"translate(-15,-10.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 2: circle */}
      <g transform={"translate(14,26) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"14,26;11.7,25.79;14,26"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={3} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 3: circle */}
      <g transform={"translate(26,24) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"26,24;24.14,24.97;26,24"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <circle cx={0} cy={0} r={3} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}