"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"24,27;18,27;24,27"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0.22 1 0.36 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0.22 1 0.36 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0.22 1 0.36 1;0 0 1 1"} additive="replace" />
            <path d="M12 19h8" transform={"translate(-16,-19)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"12.26,19.09;19.1,21.65;28.96,17.92"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 0.58 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;90,0,0;180,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 0.58 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 0.58 1;0 0 1 1"} additive="replace" />
            <path d="m4 17 6-6-6-6" transform={"translate(-7,-11)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}