"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: rect */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <rect x={-7} y={-10} width={14} height={20} rx={7} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,18.67;20,19.67;20,18.67"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1.35,1.35;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M12 6v4" transform={"translate(-12,-8)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 3: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"16.22,15.96;16.22,15.96;16.22,15.96;16.22,15.96;16.22,15.96"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3275;0.5475;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3275;0.5475;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0,0;0,0;0.03,0.03;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3275;0.5475;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M -23.24 -60 C 9.9 -60, 27.76 -33.14, 27.76 0 C 27.76 33.14, 9.9 60, -23.24 60 C -56.38 60, 30.76 33.14, 30.76 0 C 30.76 -33.14, -56.38 -60, -23.24 -60 Z" strokeDasharray={367.98} strokeDashoffset={367.98} fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="d" values="M -23.24 -60 C 9.9 -60, 27.76 -33.14, 27.76 0 C 27.76 33.14, 9.9 60, -23.24 60 C -56.38 60, 30.76 33.14, 30.76 0 C 30.76 -33.14, -56.38 -60, -23.24 -60 Z;M -23.24 -60 C 9.9 -60, 27.76 -33.14, 27.76 0 C 27.76 33.14, 9.9 60, -23.24 60 C -56.38 60, 30.76 33.14, 30.76 0 C 30.76 -33.14, -56.38 -60, -23.24 -60 Z;M -38.74 -60 C -5.6 -60, 46.26 -33.14, 46.26 0 C 46.26 33.14, -5.6 60, -38.74 60 C -71.88 60, 15.26 33.14, 15.26 0 C 15.26 -33.14, -71.88 -60, -38.74 -60 Z;M -23.24 -60 C 9.9 -60, 27.76 -33.14, 27.76 0 C 27.76 33.14, 9.9 60, -23.24 60 C -56.38 60, 30.76 33.14, 30.76 0 C 30.76 -33.14, -56.38 -60, -23.24 -60 Z;M -23.24 -60 C 9.9 -60, 27.76 -33.14, 27.76 0 C 27.76 33.14, 9.9 60, -23.24 60 C -56.38 60, 30.76 33.14, 30.76 0 C 30.76 -33.14, -56.38 -60, -23.24 -60 Z" dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3275;0.5475;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} />
              <animate attributeName="stroke-dashoffset" values={"367.98;367.98;367.98;367.98;367.98"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.3275;0.5475;0.7325;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} />
            </path>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}