"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: rect */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,14;20,14"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <rect x={-10} y={-4} width={20} height={8} rx={2} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: rect */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,26;20,26"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <rect x={-10} y={-4} width={20} height={8} rx={2} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 3: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"13.98,13.91;13.96,13.91;13.94,13.91"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 4: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"13.94,13.91;13.94,13.91;13.94,13.91"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 5: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"13.94,13.91;13.94,13.91;20.4,13.89"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 6: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20.4,13.89;20.4,13.89;20.4,13.89"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 7: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"26.74,13.97;26.76,13.97;26.76,13.97"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0,0;0.01,0.01;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 8: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20.4,13.89;20.4,13.89;20.4,13.89"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 9: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20.54,26.15;20.63,26.15;13.36,25.94"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 10: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"27.21,26.04;27.39,26.05;27.39,26.02"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.01,0.01;0,0;0.01,0.01"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 11: blob */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"13.38,25.98;13.38,25.98;13.4,25.98;13.36,25.97"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.005;0.5;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.005;0.5;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0,0;0,0;0.01,0.01;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.005;0.5;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M 0 -60 C 33.14 -60, 60 -33.14, 60 0 C 60 33.14, 33.14 60, 0 60 C -33.14 60, -60 33.14, -60 0 C -60 -33.14, -33.14 -60, 0 -60 Z" fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}