"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,20;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M2 12 L4.49 12 A2 2 0 0 0 6.41 10.54 L8.76 2.18 A0.25 0.25 0 0 1 9.24 2.18 L14.76 21.82 A0.25 0.25 0 0 0 15.24 21.82 L17.59 13.46 A2 2 0 0 1 19.52 12 L22 12" transform={"translate(-12,-12)"} strokeDasharray={49.21} strokeDashoffset={49.21} fill="none" stroke={color} strokeWidth={strokeWidth} style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"49.21;49.21;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0025;1"} keySplines={"0 0 1 1;0 0 1 1"} />
            </path>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}