"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,25.44;20,27.44;20,25.44"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1.15,1.15;1.15,1.15;1.15,1.15"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526" transform={"translate(-12,-17.44)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: circle */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,16;20,16;20,16"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.98,0.98;1.15,1.15;0.98,0.98"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <circle cx={0} cy={0} r={6} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 3: polygon */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,15.72;20,15.72;20,15.72"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;180,0,0;360,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"0.05,0.05;0.05,0.05;0.05,0.05"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <polygon points="0,-50 47.55,-15.45 29.39,40.45 -29.39,40.45 -47.55,-15.45" transform={"translate(0,4.77)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}