"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,21.5;20,21.5;20,21.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1.2,1.2;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" transform={"translate(-12,-13.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,13.5;20,12.5;20,13.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.49;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6" transform={"translate(-12,-5.5)"} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>

      {/* Element 3: rect */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,26;20,31;20,26"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4975;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <rect x={-6} y={-4} width={12} height={8} rx={1} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}