"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Group: Group */}
      <g transform={"translate(20,20) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"20,20;21,12;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.51;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;-30,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.51;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.51;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
        {/* Element 2: path */}
        <g transform={"translate(0,-6) rotate(0,0,0) scale(1,1)"}>
          <animateTransform attributeName="transform" type="translate" values={"0,-6;0,-6;0,-6"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
          <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
          <path d="M3 6h18" transform={"translate(-12,-6)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
        </g>
        {/* Element 3: path */}
        <g transform={"translate(0,-8) rotate(0,0,0) scale(1,1)"}>
          <animateTransform attributeName="transform" type="translate" values={"0,-8;0,-8;0,-8"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
          <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.5;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="sum" />
          <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" transform={"translate(-12,-4)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
        </g>
      </g>

      {/* Element 1: path */}
      <g transform={"translate(20,22) rotate(0,0,0) scale(1,1)"}>
        <animateTransform attributeName="transform" type="translate" values={"20,22;20,22"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="sum" />
        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" transform={"translate(-12,-14)"} fill="none" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>

      {/* Element 4: polygon */}
      <g transform={"translate(33.68,7.36) rotate(0,0,0) scale(0.03,0.03)"}>
        <animateTransform attributeName="transform" type="translate" values={"33.68,7.36;33.68,7.36;20.68,12.36;20.68,19.36;20.68,25.36"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4125;0.6075;0.7975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0;0,0,0;0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4125;0.6075;0.7975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <animateTransform attributeName="transform" type="scale" values={"0.03,0.03;0.03,0.03;0.03,0.03;0.03,0.03;0.03,0.03"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.4125;0.6075;0.7975;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="sum" />
        <polygon points="0,-50 39.09,-31.17 48.75,11.13 21.69,45.05 -21.69,45.05 -48.75,11.13 -39.09,-31.17" transform={"translate(0,2.48)"} fill="#bcbcbc" stroke={color} strokeWidth={strokeWidth} vectorEffect="non-scaling-stroke" style={{ opacity: 1 }} />
      </g>
      </svg>
    </div>
  );
}