"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20.1,20.07;20.1,20.07"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <path d="M7 3.5c5-2 7 2.5 3 4C1.5 10 2 15 5 16c5 2 9-10 14-7s.5 13.5-4 12c-5-2.5.5-11 6-2" transform={"translate(-12.1,-12.07)"} strokeDasharray={54.92} strokeDashoffset={54.92} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"54.92;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}