"use client";

// Auto-generated by CSSVG Editor
// Drop into any Next.js / Vite + Tailwind v3+ project.

export interface AnimatedSceneProps {
  className?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export default function AnimatedScene({
  className = "",
  size = 40,
  color = "currentColor",
  strokeWidth = 2,
}: AnimatedSceneProps = {}) {
  return (
    <div
      className={`inline-flex items-center justify-center overflow-hidden ${className}`}
      style={{ width: size, height: size, flexShrink: 0 }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 40 40"
        width={size}
        height={size}
        fill="none"
        aria-hidden="true"
      >
      {/* Element 1: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"20,20;20,20;20,20"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.925;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;-360,0,0;-360,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.925;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.925;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.925;1"} keySplines={"0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" transform={"translate(-12,-12)"} strokeDasharray={52.91} strokeDashoffset={0} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"0;0;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.925;1"} keySplines={"0 0 1 1;0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>

      {/* Element 2: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"11.82,14.97;10.63,18.91;11.18,22.86;14.02,26.66;18.53,28.82;22.21,28.56;26.3,26.79;28.96,22.13;28.87,17.54;26.55,13.42;22.15,11.03;16,11.65;13.6,13.86;13.62,13.87"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0775;0.155;0.23;0.3075;0.385;0.4625;0.5375;0.615;0.6925;0.77;0.845;0.925;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;-40,0,0;-65,0,0;-91,0,0;-112,0,0;-143,0,0;-178,0,0;-210,0,0;-244,0,0;-275,0,0;-300,0,0;-338,0,0;-355,0,0;-356,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0775;0.155;0.23;0.3075;0.385;0.4625;0.5375;0.615;0.6925;0.77;0.845;0.925;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0775;0.155;0.23;0.3075;0.385;0.4625;0.5375;0.615;0.6925;0.77;0.845;0.925;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0775;0.155;0.23;0.3075;0.385;0.4625;0.5375;0.615;0.6925;0.77;0.845;0.925;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} additive="replace" />
            <path d="M3 3v5h5" transform={"translate(-5.5,-5.5)"} strokeDasharray={10} strokeDashoffset={0} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"0;0;0;0;0;0;0;0;0;0;0;0;0;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;0.0775;0.155;0.23;0.3075;0.385;0.4625;0.5375;0.615;0.6925;0.77;0.845;0.925;1"} keySplines={"0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1;0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>

      {/* Element 3: path */}
      <g>
        <animateTransform attributeName="transform" type="translate" values={"22,18.5;22,18.5"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
        <g>
          <animateTransform attributeName="transform" type="rotate" values={"0,0,0;0,0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
          <g>
            <animateTransform attributeName="transform" type="translate" values={"0,0;0,0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <g>
              <animateTransform attributeName="transform" type="scale" values={"1,1;1,1"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} additive="replace" />
            <path d="M12 7v5l4 2" transform={"translate(-14,-10.5)"} strokeDasharray={9.47} strokeDashoffset={9.47} fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 1 }}>
              <animate attributeName="stroke-dashoffset" values={"9.47;0"} dur={"4s"} repeatCount={"indefinite"} calcMode={"spline"} keyTimes={"0;1"} keySplines={"0 0 1 1"} />
            </path>
            </g>
          </g>
        </g>
      </g>
      </svg>
    </div>
  );
}